# Serie II - Dominio de Numpy

In [12]:
! pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.


In [ ]:
import numpy as np

## E201 - Manejo de arreglos

Crea un arreglo de 20 puntos con valores aleatorios bajo la distribución normal con media 5 y desviación estándar 2.5.


In [71]:
def points_normal_distribution(mean, std, sample):
    import numpy as np
    return np.random.normal(mean, std, sample)

In [79]:
points = points_normal_distribution(5, 2.5, 20)
print(points)

[-0.64359352  3.55974783  4.95736482  1.70937173  5.60034197  0.4572933
  2.48208357  3.77356638  4.25390594  3.53868386  3.70392314  1.9635014
  1.76910538  5.76070776  2.1350208   9.39821276  5.38453419  2.3304443
  3.72845074  7.63958606]


## E202 - Operaciones de arreglos

Crea un arreglo de 100 puntos y determina la suma, el promedio, el mínimo, el máximo, la desviación estándar y los cuantiles 25%, 50% y 75%.


In [115]:
import numpy as np
random_list = list(np.random.choice(np.random.randint(0, 100), 100))
sum = np.sum(random_list)
avg = np.average(random_list)
min = np.min(random_list)
max = np.max(random_list)
std = np.std(random_list)
quantile_25 = np.quantile(random_list, 0.25)
quantile_50 = np.quantile(random_list, 0.50)
quantile_75 = np.quantile(random_list, 0.75)

print("Lista: ", random_list)
print("Suma: ", sum)
print("Promedio: ", avg)
print("Mínimo: ", min)
print("Máximo: ", max)
print("Cuantil 25%: ", quantile_25)
print("Cuantil 50%: ", quantile_50)
print("Cuantil 75%: ", quantile_75)

Lista:  [13, 0, 11, 9, 7, 11, 4, 0, 0, 8, 1, 1, 5, 1, 0, 9, 12, 0, 10, 11, 8, 9, 5, 11, 1, 11, 12, 10, 7, 4, 1, 0, 11, 10, 10, 11, 9, 9, 12, 13, 3, 0, 7, 6, 11, 12, 13, 9, 12, 11, 0, 12, 7, 8, 2, 6, 2, 1, 7, 12, 12, 1, 10, 8, 3, 7, 2, 4, 12, 8, 11, 12, 13, 8, 5, 10, 5, 2, 7, 13, 2, 6, 2, 7, 5, 1, 6, 0, 4, 3, 4, 9, 1, 0, 13, 13, 8, 7, 8, 4]
Suma:  674
Promedio:  6.74
Mínimo:  0
Máximo:  13
Cuantil 25%:  2.75
Cuantil 50%:  7.0
Cuantil 75%:  11.0


## E203 - Operaciones de matrices

Crea una matriz de 10x5 y recupera el arreglo con los valores de la primera columna, la segunda columna, la tercera columna, la cuarta columna y la quinta columna.


In [188]:
matrix = np.matrix(np.random.randint(0, 100, size = (10, 5)))
m, n = matrix.shape
print("Matriz: \n", matrix)
for i in range(n):
    print(f"Arreglo columna {i + 1}: ", np.asarray(matrix[:, i]).flatten())

Matriz: 
 [[73 18 25 12  0]
 [ 6  1 70 31 28]
 [ 8 49 35 86 76]
 [70 97 81 78 28]
 [ 0 72 17  0 17]
 [96 85 92 28  0]
 [14 94 41 24 83]
 [21 25 36  3 20]
 [15 97 79  7 61]
 [52 99 73 42 38]]
Arreglo columna 1:  [73  6  8 70  0 96 14 21 15 52]
Arreglo columna 2:  [18  1 49 97 72 85 94 25 97 99]
Arreglo columna 3:  [25 70 35 81 17 92 41 36 79 73]
Arreglo columna 4:  [12 31 86 78  0 28 24  3  7 42]
Arreglo columna 5:  [ 0 28 76 28 17  0 83 20 61 38]
